# Generated by Django 5.1.1 on 2024-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentwork',
            name='technology',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
