# Generated by Django 5.1.1 on 2024-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240923_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
