# Generated by Django 5.1.1 on 2024-09-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recentwork_slug'),
        ('core', '0006_auto_20240923_1625'),
    ]

    operations = [
    ]
