# Generated by Django 5.1.1 on 2024-09-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recentwork_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recentwork',
            name='diapo',
            field=models.FileField(blank=True, null=True, upload_to='diapos/'),
        ),
    ]
