# Generated by Django 5.1.1 on 2024-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_recentwork_code_recentwork_diapo"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentwork",
            name="github_repo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
